### ISSUE TITLE
Cannot find module 'foo' from 'bar' messages after upgrading to 1.3.2

### ISSUE THREAD

**Issue by scheinercc** [pzmosquito/eslint-import-resolver-vite#20]
Hey,

After upgrading from 1.3.1 to v1.3.2 I am getting a lot of these

```
[eslint-plugin-import:resolver:vite] Cannot find module '/[user/project/path]/public/[Component].vue' from '/[user/project/path]/resources/js/[path]'
```

Any idea what I might have to tweak?

Thanks

**Comment by pzmosquito** [comment]
Can you give '2.0.0-beta.3' a try? It looks like a bug that is fixed in the new version. Please read the [release note](https://github.com/pzmosquito/eslint-import-resolver-vite/releases/tag/2.0.0-beta.1) for upgrade instructions.

**Comment by scheinercc** [comment]
Thanks Peter. 

What is the new syntax for a `.eslintrc` file with this current config

```
"settings": {
    "import/resolver": {
      "vite": {
        "config": "./vite.configs.js"
      },
```

Also tried rewriting it into `.eslintrc.js`
```
settings: {
    'import/resolver': {
      vite: {
        config: './vite.configs.js',
        // and with
        // viteConfig: require('./vite.config').viteConfigObj,
        // and with
        // viteConfig: require('./vite.config'),
        // etc.
      },
```

witthout luck.

**Comment by scheinercc** [comment]
Scrap the above.

This seems to work fine.
```
  settings: {
    'import/resolver': {
      vite: {
        viteConfig: './vite.configs.js',
      },
```

And no more errors.
